# your informations
author:
  name: Yannick Pereira-Reis
  description: Full stack web developer <br />(Symfony, AngularJs, Docker, DevOps)
  picture: /assets/images/avatar.png

# site description
description: Thoughts and writings about Symfony2, AngularJs, Docker, Elasticsearch, gulp, javascript, freelance, Lyon, Villeurbanne

# site url
url: http://ypereirareis.github.io

# site title
title: Yannick Pereira-Reis - Full stask lead developer Symfony2, AngularJs and play with DevOps tools like vagrant, docker, supervisor, elasticsearch, elk, freelance, Lyon

# site version
version: 1.0.0

# number of posts per page
paginate: 10

# your github username
github_username: ypereirareis

# Twitter
twitter_username: "@yannickpr69"

# linkedin url
linkedin_url: fr.linkedin.com/in/yannickpereirareis

# set true to include or false to exclude share option
share:
  twitter: true
  google_plus: true
  linkedin: true
  disqus: true


# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
disqus_username: ypereirareisgithubio
disqus_api_key: XSyglG1uPhzx9toLacpmIqEPcWY6XeZXohwsrLfmDqV8qdPr0EsFkq0prHY3n7Iq
disqus_recent_comments_to_display: 10

markdown: kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]


permalink: /blog/:year/:month/:day/:title
