# your informations
author:
  name: Yannick Pereira-Reis
  description: Frontend and Backend web developer
  picture: /assets/images/avatar.png

# site description
description: Thoughts and writings about software engineering by Yannick Pereira-Reis.

# site url
url: http://ypereirareis.github.io

# site title
title: Yannick Pereira-Reis

# site version
version: 1.0.0

# number of posts per page
paginate: 5

# your github username
github_username: ypereirareis

# linkedin url
linkedin_url: fr.linkedin.com/in/yannickpereirareis

# set true to include or false to exclude share option
share:
  twitter: true
  google_plus: true
  linkedin: true
  disqus: true


# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
disqus_username: ypereirareisgithubio
disqus_api_key: XSyglG1uPhzx9toLacpmIqEPcWY6XeZXohwsrLfmDqV8qdPr0EsFkq0prHY3n7Iq
disqus_recent_comments_to_display: 10

markdown: kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]


permalink: /blog/:year/:month/:day/:title.html
