
version: "2"
services:
  web:
    image: jekyll/jekyll:3.6
    working_dir: /srv/jekyll
    command: jekyll serve -H0.0.0.0
    volumes:
      - .:/srv/jekyll
      - ./cache:/usr/local/bundle
    ports:
      - "127.0.0.1:4000:4000"


